# vi: set fenc=utf-8 ft=yaml ts=8 sw=2 sts=2 et:
# coding: utf-8

# Copyright (c) 2017 eyeo GmbH
#
# This is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the software. If not, see <http://www.gnu.org/licenses/>.

# http://docs.ansible.com/ansible/latest/playbooks.html
---
- hosts: "all"

  # http://docs.ansible.com/ansible/latest/playbooks_intro.html#tasks-list
  tasks:

    # http://docs.ansible.com/ansible/package_module.html
    - name: "package git"
      package:
        name: "git"
        state: "installed"
    - name: "package mercurial"
      package:
        name: "mercurial"
        state: "installed"

    # http://docs.ansible.com/ansible/stat_module.html
    - name: "stat /vagrant"
      stat:
        path: "/vagrant"
      register: "vagrant"

    # http://docs.ansible.com/ansible/stat_module.html
    - name: "file /tmp/ansible-example"
      copy:
        content: "ansible-example"
        dest: "/tmp/ansible-example"
      when:
        - "vagrant.stat.exists == False"

  # http://docs.ansible.com/ansible/playbooks_intro.html#handlers
  handlers:

    # http://docs.ansible.com/ansible/debug_module.html
    - name: "handler example"
      debug:
        msg: "Hello world!"

  # http://docs.ansible.com/ansible/become.html
  become: true

